mengambar persamaan bidang dalam 3D
1. 8x1 + x2

## penyelesain sistem linier menggunakan sistem eliminasi gauss

pertama kita
selesaikan solusi persamaan berikut!
$$
8x_1 + 9x_2 x_3 = 19\\
x_1 + 2x_2 + 3x_3 = 9\\
2x_1 +x_2+x_3 = 5\
$$

berikut penyelesaian perssamaan diatas

In [ ]:
import numpy as np
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])

print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


mendefinisikan fungsi operasi baris elimiasi gauss

*rowswaap()
*rowscale()
*rowAdd


In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

tahapan penyelessaian dengan mneggunakan eliminasi gauss

In [ ]:
## tukar baris 1 dengan baris 2
A1 = RowSwap(A,0,1)
print(A1,'\n')

##tambahkan kali-3 baris 0 dengan baris 1
A2 = RowAdd(A1,0,1,-8)
print(A2,"\n")

A3 = RowAdd(A2,0,2,-2)
print(A3,"\n")
A4 = RowAdd(A3,2,1,-2)
print(A4,"\n")
A5 = RowScale(A4,1,-1)
print(A5,"\n")
A6 = RowAdd(A5,1,2,3)
print(A6,"\n")
A7 = RowScale(A6,2,1/34)
print(A7,"\n")
A8 = RowAdd(A7,2,1,-12)
print(A8,"\n")

[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]] 

[[  1.   2.   3.   9.]
 [  0.  -1. -13. -27.]
 [  0.  -3.  -5. -13.]] 

[[  1.   2.   3.   9.]
 [ -0.   1.  13.  27.]
 [  0.  -3.  -5. -13.]] 

[[ 1.  2.  3.  9.]
 [-0.  1. 13. 27.]
 [ 0.  0. 34. 68.]] 

[[ 1.  2.  3.  9.]
 [-0.  1. 13. 27.]
 [ 0.  0.  1.  2.]] 

[[ 1.  2.  3.  9.]
 [-0.  1.  1.  3.]
 [ 0.  0.  1.  2.]] 



In [9]:
!cd /content/drive/MyDrive/Alin/

In [10]:
!pip install jupyter-book

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.2/77.2 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 12.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 28.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 45.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.7/572.7 kB 39.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.4/561.4 kB 39.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 40.5 MB/s eta 0:00:00
  Attempting uninstall: docutils
    Found existing installation: docutils 0.18.1
    Uninstalling docutils-0.18.1:

selamat bertugas