mengambar persamaan bidang dalam 3D
1. 8x1 + x2

## penyelesain sistem linier menggunakan sistem eliminasi gauss

pertama kita
selesaikan solusi persamaan berikut!
$$
8x_1 + 9x_2+x_3 = 19\\
x_1 + 2x_2 + 3x_3 = 9\\
2x_1 +x_2+x_3 = 5\
$$

berikut penyelesaian perssamaan diatas

In [ ]:
import numpy as np
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])

print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


mendefinisikan fungsi operasi baris elimiasi gauss

*rowswaap()
menukar posisi baris
*rowscale()
mengalikan suatu baris
*rowAdd
mengalikan suatu baris dan menambahkan hasilnya ke baris lainnya


In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

tahapan penyelessaian dengan mneggunakan eliminasi gauss

In [ ]:
## tukar baris 1 dengan baris 2
A1 = RowSwap(A,0,1)
print(A1,'\n')

##tambahkan kali-3 baris 0 dengan baris 1
A2 = RowAdd(A1,0,1,-8)
print(A2,"\n")

A3 = RowAdd(A2,0,2,-2)
print(A3,"\n")
A4 = RowAdd(A3,2,1,-2)
print(A4,"\n")
A5 = RowScale(A4,1,-1)
print(A5,"\n")
A6 = RowAdd(A5,1,2,3)
print(A6,"\n")
A7 = RowScale(A6,2,1/34)
print(A7,"\n")
A8 = RowAdd(A7,2,1,-12)
print(A8,"\n")

[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]] 

[[  1.   2.   3.   9.]
 [  0.  -1. -13. -27.]
 [  0.  -3.  -5. -13.]] 

[[  1.   2.   3.   9.]
 [ -0.   1.  13.  27.]
 [  0.  -3.  -5. -13.]] 

[[ 1.  2.  3.  9.]
 [-0.  1. 13. 27.]
 [ 0.  0. 34. 68.]] 

[[ 1.  2.  3.  9.]
 [-0.  1. 13. 27.]
 [ 0.  0.  1.  2.]] 

[[ 1.  2.  3.  9.]
 [-0.  1.  1.  3.]
 [ 0.  0.  1.  2.]] 



In [ ]:
import numpy as np
B=np.array([[3,-2,-3,5],[1,1,-2,3],[1,-1,1,-4]])

print(B)

[[ 3 -2 -3  5]
 [ 1  1 -2  3]
 [ 1 -1  1 -4]]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Membuat data untuk bidang
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)
x, y = np.meshgrid(x, y)

# Persamaan bidang
z1 = (1 - 2*x - 3*y) / 9
z2 = (x + y) / 3
z3 = (y) / 2

# Plotting
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plot bidang
ax.plot_surface(x, y, z1, alpha=0.5, rstride=100, cstride=100)
ax.plot_surface(x, y, z2, alpha=0.5, rstride=100, cstride=100)
ax.plot_surface(x, y, z3, alpha=0.5, rstride=100, cstride=100)

# Menandai titik potong
ax.scatter(1, 1, 1, color='red', s=100, label='Titik Potong')

# Label sumbu
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

# Menampilkan plot
plt.legend()
plt.show()

tugas membuat soal sendiri

In [ ]:
B1 = RowSwap(B,0,1)
print(B1,'\n')

B2 = RowAdd(B1,0,1,-3)
print(B2,'\n')
B3 = RowAdd(B2,0,2,-1)
print(B3,'\n')
B4 = RowAdd(B3,2,1,-3)
print(B4,'\n')
B5 = RowAdd(B4,1,2,2)
print(B5,'\n')
B6 = RowScale(B5,2,1/9)
print(B6,'\n')
B7 = RowAdd(B6,2,1,-5)
print(B7,'\n')

[[ 1.  1. -2.  3.]
 [ 3. -2. -3.  5.]
 [ 1. -1.  1. -4.]] 

[[ 1.  1. -2.  3.]
 [ 0. -5.  3. -4.]
 [ 1. -1.  1. -4.]] 

[[ 1.  1. -2.  3.]
 [ 0. -5.  3. -4.]
 [ 0. -2.  3. -7.]] 

[[ 1.  1. -2.  3.]
 [ 0.  1. -6. 17.]
 [ 0. -2.  3. -7.]] 

[[ 1.  1. -2.  3.]
 [ 0.  1. -6. 17.]
 [ 0.  0. -9. 27.]] 

[[ 1.  1. -2.  3.]
 [ 0.  1. -6. 17.]
 [ 0.  0. -1.  3.]] 

[[ 1.  1. -2.  3.]
 [ 0.  1. -1.  2.]
 [ 0.  0. -1.  3.]] 

