## aljabar matrik
- berikan penjelasan tentang apa itu matrik
- operasi matrik
- buat program untuk mengalikan matrik A dan B

syaa disuruh bikin matrik A dan B ukuran 3X3 dan matrik c dengan unkuran 3x2
m x n adalah matrik A
n x k adalah matrik B

In [2]:
import numpy as np
import sympy as sy

In [5]:
import numpy as np
A = np.array([[2,5,3],[2,6,3],[7,9,2]])
print(A)
B = np.array([[2,1,4],[7,3,6],[2,6,5]])
print(B)
C = np.array([[2,4],[3,6],[7,2]])
print(C)
D = np.array([[8,4,4],[2,5,6],[7,2,5]])
print(D)

print(a@C)

[[2 5 3]
 [2 6 3]
 [7 9 2]]
[[2 1 4]
 [7 3 6]
 [2 6 5]]
[[2 4]
 [3 6]
 [7 2]]
[[8 4 4]
 [2 5 6]
 [7 2 5]]
[[ 4  6  7]
 [ 9  9  9]
 [ 9 15  7]]
[[ 4 10  6]
 [ 4 12  6]
 [14 18  4]]
[[40 44]
 [43 50]
 [55 86]]
(3, 2)
