## aljabar matrik
- berikan penjelasan tentang apa itu matrik
- operasi matrik(pertambahan, pengurangan dan pemrkalian)
- buat program untuk mengalikan matrik A dan B
- pertambahan pengurangan perkalian dan transpose matrik
syaa disuruh bikin matrik A dan B ukuran 3X3 dan matrik c dengan unkuran 3x2
m x n adalah matrik A
n x k adalah matrik B

In [ ]:
import numpy as np
import sympy as sy

In [2]:
import numpy as np
A = np.array([[2,5,3],[2,6,3],[7,9,2]])
print(A)
B = np.array([[2,1,4],[7,3,6],[2,6,5]])
print(B)
C = np.array([[2,4],[3,6],[7,2]])
print(C)
D = np.array([[8,4,4],[2,5,6],[7,2,5]])
print(D)

print(A@C)

[[2 5 3]
 [2 6 3]
 [7 9 2]]
[[2 1 4]
 [7 3 6]
 [2 6 5]]
[[2 4]
 [3 6]
 [7 2]]
[[8 4 4]
 [2 5 6]
 [7 2 5]]
[[40 44]
 [43 50]
 [55 86]]


Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung.

# operasi matriks
## penjumlahan
 penjuamlahan matriks dapat dilakukan jika panjang baris dan kolomm kedua matriks sama
cara menjumlahkannya cukup menambahkan matriks pertama dan kedua pada tiap baris dan kolom yang sama
## pengurangan
 sama seperti penjumlahan hanya saja idkurangi
## perkalian
perkalian matriks hanya dapat dilakukan jika kolom matriks A sama dengan baris matrik B
matriks dari hasil perkalian matriks akan memiliki jumlah baris
yang sama dengan matrik pertama dan jumlah kolom yang sama dengan matrik kedua
perkalian matrik A x B berbeda dengan perkalian matrik B x A
##transpose matrik
transpose matrik adalah matrik yang posisi baris dan kolomnya bertukar posisi  
transpose matriks biasanya diandai dengan tanda pangkat t pada matriks tersebut

In [11]:
result = [[0, 0 , 0],
          [0, 0 , 0],
          [0, 0 , 0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]



for row in result:
  print(row)
k = 0
Y = []
for i in range (len(A)):
  Z = []
  for j in range(len(B[0])):
    Z.append(A[i,0]*B[0,j]+A[i,1]*B[1,j]+A[i,2]*B[2,j])
  Y+=[Z]

Y=np.array(Y)
print(Y)
print(A@B)

[[45 35]
 [52 38]
 [81 46]]
[[45 35 53]
 [52 38 59]
 [81 46 92]]
[[40 44]
 [43 50]
 [55 86]]


Hasil perkalian matriks A dan B:
[[45, 35, 53], [52, 38, 59], [81, 46, 92]]


matrik adalah

contoh dibawah matik A dan matrik B

$\begin{align*}
A=
\begin{bmatrix}
2&-3&4\\
1&0&-7
\end{bmatrix}
&&
B=
\begin{bmatrix}
6&2&-4\\
3&5&2
\end{bmatrix}
\end{align*}$

$\begin{align*}
\matrixentry{A+B}{ij}&=\matrixentry{A}{ij}+\matrixentry{B}{ij}
&&1\leq i\leq m,\,1\leq j\leq n
\end{align*}$